#!/usr/bin/env python3
"""Generate a single TeX root that assembles all LRA volumes."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path

from assemble_reference_tex import _walk


ROMANS = ("i", "ii", "iii", "iv", "v", "vi", "vii", "viii")
ROMAN_DISPLAY = {
    "i": "I",
    "ii": "II",
    "iii": "III",
    "iv": "IV",
    "v": "V",
    "vi": "VI",
    "vii": "VII",
    "viii": "VIII",
}


@dataclass(frozen=True)
class VolumeSpec:
    roman: str
    title: str
    root: Path
    bibliography_stems: tuple[str, ...]
    books: tuple["BookSpec", ...]

    @property
    def display(self) -> str:
        return f"Volume {ROMAN_DISPLAY[self.roman]}: {self.title}"


@dataclass(frozen=True)
class BookSpec:
    title: str
    tex_root: Path
    book_dir: str
    bibliography_stem: str


def _extract_braced_argument(text: str, start: int) -> tuple[str, int]:
    if start >= len(text) or text[start] != "{":
        raise ValueError("expected braced argument")
    depth = 0
    chars: list[str] = []
    i = start
    while i < len(text):
        char = text[i]
        if char == "{" and (i == 0 or text[i - 1] != "\\"):
            depth += 1
            if depth > 1:
                chars.append(char)
        elif char == "}" and (i == 0 or text[i - 1] != "\\"):
            depth -= 1
            if depth == 0:
                return "".join(chars), i + 1
            chars.append(char)
        else:
            chars.append(char)
        i += 1
    raise ValueError("unterminated braced argument")


def _parse_frontmatter_title(root_tex: Path) -> str:
    text = root_tex.read_text(encoding="utf-8")
    marker = r"\LRAFrontMatterPage"
    start = text.find(marker)
    if start == -1:
        return root_tex.stem
    cursor = start + len(marker)
    try:
        _, cursor = _extract_braced_argument(text, cursor)
        title, _ = _extract_braced_argument(text, cursor)
    except ValueError:
        return root_tex.stem
    return title.strip() or root_tex.stem


def _parse_bibliography_stems(root_tex: Path) -> tuple[str, ...]:
    text = root_tex.read_text(encoding="utf-8")
    match = re.search(r"\\bibliography\s*\{(?P<body>.*?)\}", text, flags=re.DOTALL)
    if not match:
        return ()
    body = re.sub(r"%.*", "", match.group("body"))
    stems = [item.strip() for item in body.replace("\n", "").split(",")]
    return tuple(stem for stem in stems if stem)


def discover_volumes(repos_root: Path, requested: list[str] | None = None) -> list[VolumeSpec]:
    registry = json.loads((Path(__file__).resolve().parents[2] / "docs" / "architecture" / "book-registry.json").read_text(encoding="utf-8"))
    registry_by_roman = {volume.get("roman"): volume for volume in registry.get("volumes", [])}
    romans = tuple(requested) if requested else ROMANS
    volumes: list[VolumeSpec] = []
    for roman in romans:
        if roman not in ROMANS:
            raise SystemExit(f"unsupported volume roman numeral: {roman}")
        root = repos_root / f"lra-volume-{roman}"
        root_tex = root / f"volume-{roman}.tex"
        index = root / f"volume-{roman}" / "index.tex"
        if not root_tex.exists() or not index.exists():
            raise SystemExit(f"missing volume root or index for volume-{roman}: {root}")
        volume_registry = registry_by_roman.get(roman) or {}
        books: list[BookSpec] = []
        for book in sorted(volume_registry.get("books", []), key=lambda item: int(item.get("order", 0))):
            tex_root_name = str(book.get("tex_root") or "")
            book_dir = str(book.get("book_dir") or "")
            title = str(book.get("title") or tex_root_name)
            if not tex_root_name or not book_dir:
                raise SystemExit(f"incomplete book registry entry for volume-{roman}: {book!r}")
            tex_root = root / tex_root_name
            if not tex_root.exists():
                raise SystemExit(f"missing book TeX root for volume-{roman}: {tex_root}")
            books.append(
                BookSpec(
                    title=title,
                    tex_root=tex_root,
                    book_dir=book_dir,
                    bibliography_stem=f"bibliography/{tex_root.stem}",
                )
            )
        volumes.append(
            VolumeSpec(
                roman=roman,
                title=_parse_frontmatter_title(root_tex),
                root=root,
                bibliography_stems=_parse_bibliography_stems(root_tex),
                books=tuple(books),
            )
        )
    return volumes


def _common_preamble(
    title: str,
    subtitle: str,
    document_class: str = "12pt, a4paper",
    extra_preamble: list[str] | None = None,
) -> list[str]:
    lines = [
        "% =========================================================",
        "% Generated by lra-governance/tools/governance/assemble_all_volumes_tex.py",
        "% Do not edit this generated build root by hand.",
        "% =========================================================",
        rf"\documentclass[{document_class}]{{report}}",
        r"\input{common/volume-preamble}",
        r"\renewcommand{\LRALoadExternalReferences}{}",
        r"\providecommand{\book}[1]{%",
        r"  \cleardoublepage",
        r"  \phantomsection",
        r"  \addcontentsline{toc}{chapter}{#1}%",
        r"  {\centering\Huge\bfseries #1\par}%",
        r"  \vspace{2\baselineskip}%",
        r"}",
        "",
    ]
    lines.extend(extra_preamble or [])
    lines.extend([
        "",
        r"\begin{document}",
        r"\ExplSyntaxOff",
        r"\renewcommand{\familydefault}{\rmdefault}",
        "",
        r"\pagenumbering{roman}",
        rf"\begin{{titlepage}}\centering",
        r"\vspace*{0.22\textheight}",
        rf"{{\Huge\bfseries {title}\par}}",
        r"\vspace{2em}",
        rf"{{\Large {subtitle}\par}}",
        r"\end{titlepage}",
        "",
        r"\tableofcontents",
        r"\clearpage",
        r"\pagenumbering{arabic}",
        r"\LraEnableFooterBreadcrumb",
        "",
    ])
    return lines


def tex_for(volumes: list[VolumeSpec], title: str) -> str:
    bibliography = []
    for volume in volumes:
        bibliography.extend(volume.bibliography_stems)

    lines = _common_preamble(title, "Combined all-volume build")

    for volume in volumes:
        lines.extend(
            [
                r"\cleardoublepage",
                rf"\part{{{volume.display}}}",
                r"\microtypesetup{expansion=false}",
                "",
            ]
        )
        for book in volume.books:
            lines.extend(
                [
                    rf"\book{{{book.title}}}",
                    rf"\input{{{book.book_dir}/index}}",
                    r"\clearpage",
                    "",
                ]
            )
        lines.extend(
            [
                r"\microtypesetup{expansion=true}",
                "",
            ]
        )

    lines.extend(
        [
            r"\clearpage",
            r"\bibliographystyle{plainnat}",
        ]
    )
    if bibliography:
        lines.append(r"\bibliography{%")
        for index, stem in enumerate(bibliography):
            suffix = "," if index < len(bibliography) - 1 else ""
            lines.append(f"  {stem}{suffix}%")
        lines.append("}")
    lines.extend(
        [
            "",
            r"\printindex[tech]",
            r"\printindex[dep]",
            "",
            r"\end{document}",
            "",
        ]
    )
    return "\n".join(lines)


def reference_tex_for(volumes: list[VolumeSpec], title: str) -> str:
    lines = _common_preamble(
        title,
        "Combined definition and theorem reference",
        "10pt, a4paper",
        [
            r"\lrasetup{edition=reference}",
            r"\setlength{\parskip}{2pt}",
            r"\setlength{\parindent}{0pt}",
        ],
    )

    for volume in volumes:
        lines.extend([r"\cleardoublepage", rf"\part{{{volume.display}}}", ""])
        volume_root = volume.root / f"volume-{volume.roman}"
        for book in volume.books:
            items = _walk(book.tex_root, volume_root, set())
            if not items:
                raise SystemExit(f"no reference blocks found while scanning {book.tex_root}")
            lines.extend([rf"\book{{{book.title}}}", ""])
            for item in items:
                try:
                    source = item.path.relative_to(volume.root).as_posix()
                except ValueError:
                    source = item.path.as_posix()
                lines.extend([f"% Source: {source}:{item.line}", item.text, ""])

    lines.extend([r"\end{document}", ""])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate an all-volume LRA TeX root.")
    parser.add_argument("--repos-root", type=Path, default=Path("/lra-repos"))
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--title", default="Learning Real Analysis")
    parser.add_argument("--edition", choices=("digital", "print", "reference"), default="digital")
    parser.add_argument(
        "--volume",
        action="append",
        choices=ROMANS,
        help="volume roman numeral to include; repeatable. Defaults to all volumes.",
    )
    args = parser.parse_args(argv)

    repos_root = args.repos_root.expanduser().resolve()
    volumes = discover_volumes(repos_root, args.volume)
    output = args.out.expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    text = reference_tex_for(volumes, args.title) if args.edition == "reference" else tex_for(volumes, args.title)
    output.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    for volume in volumes:
        print(f"  - {volume.display}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
