#!/usr/bin/env python3
"""Generate a single TeX root that assembles all LRA volumes."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


ROMANS = ("i", "ii", "iii", "iv", "v", "vi", "vii", "viii")
ROMAN_DISPLAY = {
    "i": "I",
    "ii": "II",
    "iii": "III",
    "iv": "IV",
    "v": "V",
    "vi": "VI",
    "vii": "VII",
    "viii": "VIII",
}


@dataclass(frozen=True)
class VolumeSpec:
    roman: str
    title: str
    root: Path
    bibliography_stems: tuple[str, ...]

    @property
    def display(self) -> str:
        return f"Volume {ROMAN_DISPLAY[self.roman]}: {self.title}"


def _extract_braced_argument(text: str, start: int) -> tuple[str, int]:
    if start >= len(text) or text[start] != "{":
        raise ValueError("expected braced argument")
    depth = 0
    chars: list[str] = []
    i = start
    while i < len(text):
        char = text[i]
        if char == "{" and (i == 0 or text[i - 1] != "\\"):
            depth += 1
            if depth > 1:
                chars.append(char)
        elif char == "}" and (i == 0 or text[i - 1] != "\\"):
            depth -= 1
            if depth == 0:
                return "".join(chars), i + 1
            chars.append(char)
        else:
            chars.append(char)
        i += 1
    raise ValueError("unterminated braced argument")


def _parse_frontmatter_title(root_tex: Path) -> str:
    text = root_tex.read_text(encoding="utf-8")
    marker = r"\LRAFrontMatterPage"
    start = text.find(marker)
    if start == -1:
        return root_tex.stem
    cursor = start + len(marker)
    try:
        _, cursor = _extract_braced_argument(text, cursor)
        title, _ = _extract_braced_argument(text, cursor)
    except ValueError:
        return root_tex.stem
    return title.strip() or root_tex.stem


def _parse_bibliography_stems(root_tex: Path) -> tuple[str, ...]:
    text = root_tex.read_text(encoding="utf-8")
    match = re.search(r"\\bibliography\s*\{(?P<body>.*?)\}", text, flags=re.DOTALL)
    if not match:
        return ()
    body = re.sub(r"%.*", "", match.group("body"))
    stems = [item.strip() for item in body.replace("\n", "").split(",")]
    return tuple(stem for stem in stems if stem)


def discover_volumes(repos_root: Path, requested: list[str] | None = None) -> list[VolumeSpec]:
    romans = tuple(requested) if requested else ROMANS
    volumes: list[VolumeSpec] = []
    for roman in romans:
        if roman not in ROMANS:
            raise SystemExit(f"unsupported volume roman numeral: {roman}")
        root = repos_root / f"lra-volume-{roman}"
        root_tex = root / f"volume-{roman}.tex"
        index = root / f"volume-{roman}" / "index.tex"
        if not root_tex.exists() or not index.exists():
            raise SystemExit(f"missing volume root or index for volume-{roman}: {root}")
        volumes.append(
            VolumeSpec(
                roman=roman,
                title=_parse_frontmatter_title(root_tex),
                root=root,
                bibliography_stems=_parse_bibliography_stems(root_tex),
            )
        )
    return volumes


def tex_for(volumes: list[VolumeSpec], title: str) -> str:
    bibliography = []
    for volume in volumes:
        bibliography.extend(volume.bibliography_stems)

    lines = [
        "% =========================================================",
        "% Generated by lra-governance/tools/governance/assemble_all_volumes_tex.py",
        "% Do not edit this generated build root by hand.",
        "% =========================================================",
        r"\documentclass[12pt, a4paper]{report}",
        r"\input{common/volume-preamble}",
        r"\renewcommand{\LRALoadExternalReferences}{}",
        "",
        r"\begin{document}",
        r"\ExplSyntaxOff",
        r"\renewcommand{\familydefault}{\rmdefault}",
        "",
        r"\pagenumbering{roman}",
        rf"\begin{{titlepage}}\centering",
        r"\vspace*{0.22\textheight}",
        rf"{{\Huge\bfseries {title}\par}}",
        r"\vspace{2em}",
        r"{\Large Combined all-volume build\par}",
        r"\end{titlepage}",
        "",
        r"\tableofcontents",
        r"\clearpage",
        r"\pagenumbering{arabic}",
        r"\LraEnableFooterBreadcrumb",
        "",
    ]

    for volume in volumes:
        lines.extend(
            [
                r"\cleardoublepage",
                rf"\part*{{{volume.display}}}",
                rf"\addcontentsline{{toc}}{{part}}{{{volume.display}}}",
                rf"\input{{volume-{volume.roman}/index}}",
                "",
            ]
        )

    lines.extend(
        [
            r"\clearpage",
            r"\bibliographystyle{plainnat}",
        ]
    )
    if bibliography:
        lines.append(r"\bibliography{%")
        for index, stem in enumerate(bibliography):
            suffix = "," if index < len(bibliography) - 1 else ""
            lines.append(f"  {stem}{suffix}%")
        lines.append("}")
    lines.extend(
        [
            "",
            r"\printindex[tech]",
            r"\printindex[dep]",
            "",
            r"\end{document}",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate an all-volume LRA TeX root.")
    parser.add_argument("--repos-root", type=Path, default=Path("/lra-repos"))
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--title", default="Learning Real Analysis")
    parser.add_argument(
        "--volume",
        action="append",
        choices=ROMANS,
        help="volume roman numeral to include; repeatable. Defaults to all volumes.",
    )
    args = parser.parse_args(argv)

    repos_root = args.repos_root.expanduser().resolve()
    volumes = discover_volumes(repos_root, args.volume)
    output = args.out.expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(tex_for(volumes, args.title), encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    for volume in volumes:
        print(f"  - {volume.display}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
