#!/usr/bin/env python3
"""Generate compact reference TeX roots from routed LRA volume source."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

from core.file_inventory import input_candidates
from core.tex import INPUT_RE, strip_latex_comments
from core.volume import is_ignored, resolve_volume


REFERENCE_ENVS = ("definition", "theorem", "lemma", "proposition", "corollary")
BEGIN_REFERENCE_RE = re.compile(
    r"\\begin\{(?P<env>" + "|".join(REFERENCE_ENVS) + r")\}(?:\[[^\]]*\])?",
    re.IGNORECASE,
)
SECTIONING_RE = re.compile(
    r"\\(?P<cmd>part|chapter|section|subsection|subsubsection)\*?(?:\[[^\]]*\])?\{",
    re.IGNORECASE,
)
SKIPPED_ROUTE_PARTS = {
    "bibliography",
    "build",
    "common",
    "frontmatter",
    "images",
    "proofs",
}


@dataclass(frozen=True)
class ReferenceItem:
    path: Path
    line: int
    text: str


def _line_at(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def _extract_balanced_braced(text: str, open_brace: int) -> int | None:
    depth = 0
    index = open_brace
    while index < len(text):
        char = text[index]
        escaped = index > 0 and text[index - 1] == "\\"
        if char == "{" and not escaped:
            depth += 1
        elif char == "}" and not escaped:
            depth -= 1
            if depth == 0:
                return index + 1
        index += 1
    return None


def _extract_reference_block(text: str, match: re.Match[str]) -> str | None:
    env = match.group("env")
    end_re = re.compile(rf"\\end\{{{re.escape(env)}\}}", re.IGNORECASE)
    end = end_re.search(text, match.end())
    if end is None:
        return None
    return text[match.start() : end.end()].strip()


def _extract_sectioning(text: str, match: re.Match[str]) -> str | None:
    end = _extract_balanced_braced(text, match.end() - 1)
    if end is None:
        return None
    command = match.group("cmd").lower()
    source = text[match.start() : end].strip()
    if command in {"part", "chapter"}:
        return source.replace(f"\\{command}", f"\\{command}*", 1)
    return source


def _should_skip(path: Path, volume_root: Path) -> bool:
    if is_ignored(path, volume_root):
        return True
    try:
        parts = set(path.resolve().relative_to(volume_root.resolve()).parts)
    except ValueError:
        parts = set(path.parts)
    return bool(parts & SKIPPED_ROUTE_PARTS)


def _resolve_input(source: Path, volume_root: Path, target: str) -> Path | None:
    normalized = target.replace("\\", "/").removesuffix(".tex")
    for candidate in input_candidates(normalized, source, volume_root):
        if candidate.exists() and candidate.is_file():
            resolved = candidate.resolve()
            if not _should_skip(resolved, volume_root):
                return resolved
    return None


def _walk(path: Path, volume_root: Path, seen: set[Path]) -> list[ReferenceItem]:
    resolved = path.resolve()
    if resolved in seen or _should_skip(resolved, volume_root):
        return []
    seen.add(resolved)

    raw = resolved.read_text(encoding="utf-8", errors="replace")
    uncommented = strip_latex_comments(raw)
    events: list[tuple[int, str, object]] = []
    for match in INPUT_RE.finditer(uncommented):
        target = _resolve_input(resolved, volume_root, match.group(1))
        if target is not None:
            events.append((match.start(), "input", target))
    for match in SECTIONING_RE.finditer(raw):
        sectioning = _extract_sectioning(raw, match)
        if sectioning is not None:
            events.append((match.start(), "item", sectioning))
    for match in BEGIN_REFERENCE_RE.finditer(raw):
        block = _extract_reference_block(raw, match)
        if block is not None:
            events.append((match.start(), "item", block))

    items: list[ReferenceItem] = []
    for offset, kind, payload in sorted(events, key=lambda item: item[0]):
        if kind == "input":
            items.extend(_walk(payload, volume_root, seen))  # type: ignore[arg-type]
        else:
            items.append(ReferenceItem(resolved, _line_at(raw, offset), str(payload)))
    return items


def reference_tex(volume_repo: Path, tex_root: Path, items: list[ReferenceItem]) -> str:
    title = tex_root.stem.replace("-", " ").title()
    lines = [
        "% =========================================================",
        "% Generated by lra-governance/tools/governance/assemble_reference_tex.py",
        "% Do not edit this generated reference root by hand.",
        "% =========================================================",
        r"\documentclass[10pt, a4paper]{report}",
        r"\input{common/volume-preamble}",
        r"\renewcommand{\LRALoadExternalReferences}{}",
        r"\lrasetup{edition=reference}",
        r"\setlength{\parskip}{2pt}",
        r"\setlength{\parindent}{0pt}",
        "",
        r"\begin{document}",
        r"\ExplSyntaxOff",
        r"\renewcommand{\familydefault}{\rmdefault}",
        rf"\begin{{center}}{{\Large\bfseries {title} Reference}}\end{{center}}",
        r"\tableofcontents",
        r"\clearpage",
        "",
    ]
    for item in items:
        try:
            source = item.path.relative_to(volume_repo).as_posix()
        except ValueError:
            source = item.path.as_posix()
        lines.extend([f"% Source: {source}:{item.line}", item.text, ""])
    lines.append(r"\end{document}")
    lines.append("")
    return "\n".join(lines)


def generate_reference_roots(volume_repo: Path, tex_roots: list[Path], output_dir: Path) -> list[Path]:
    volume = resolve_volume(volume_repo)
    output_dir.mkdir(parents=True, exist_ok=True)
    generated: list[Path] = []
    for tex_root in tex_roots:
        items = _walk(tex_root, volume.root, set())
        if not items:
            raise SystemExit(f"no reference blocks found while scanning {tex_root}")
        output = output_dir / f"{tex_root.stem}-reference.tex"
        output.write_text(reference_tex(volume.source, tex_root, items), encoding="utf-8", newline="\n")
        print(f"wrote {output} ({len(items)} reference item(s))")
        generated.append(output)
    return generated


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate compact LRA reference TeX roots.")
    parser.add_argument("--root", type=Path, default=Path("."), help="volume repository root")
    parser.add_argument("--out-dir", type=Path, default=Path("build") / "reference")
    parser.add_argument("--tex-root", action="append", required=True, help="TeX root relative to --root")
    args = parser.parse_args(argv)

    volume_repo = args.root.expanduser().resolve()
    tex_roots = [(volume_repo / root).resolve() for root in args.tex_root]
    missing = [root for root in tex_roots if not root.exists()]
    if missing:
        raise SystemExit("missing TeX root(s): " + ", ".join(str(path) for path in missing))
    generate_reference_roots(volume_repo, tex_roots, (volume_repo / args.out_dir).resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
