#!/usr/bin/env python3
"""Map LRA repositories to their canonical overlays.

The canonical per-repo overlay is capabilities/overlays/<repo>.md, and the
repo registry is capabilities/overlays-config.yaml. Volume overlays are
generated by capabilities/generate_overlays.py; every other overlay is
hand-maintained.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

GOVERNANCE_ROOT = Path(__file__).resolve().parents[2]


@lru_cache(maxsize=1)
def _config_repos() -> tuple[str, ...]:
    import yaml

    config_path = GOVERNANCE_ROOT / "capabilities" / "overlays-config.yaml"
    config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    return tuple(str(record["repo"]) for record in config.get("repos", []))


def repo_names() -> list[str]:
    return list(_config_repos())


def overlay_for_repo(repo: str) -> str:
    if repo not in _config_repos():
        raise KeyError(f"unknown LRA repo: {repo}")
    return f"{repo}.md"


def overlay_path(repo: str, governance_root: Path) -> Path:
    return governance_root / "capabilities" / "overlays" / overlay_for_repo(repo)


def load_overlay(repo: str, governance_root: Path) -> str:
    return overlay_path(repo, governance_root).read_text(encoding="utf-8")
