#!/usr/bin/env python3
"""Plan or apply conservative TeX -> Lean formalization tags.

This tool consumes an internal object index generated by
``index_internal_objects.py``.  It only proposes exact title-to-declaration
matches, requires a TeX label, and defaults to production Lean paths under
``LRA/``.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml

try:
    from index_internal_objects import kind_compatible, normalize_match_key
except ModuleNotFoundError:  # pragma: no cover - exercised by package imports
    from tools.governance.index_internal_objects import kind_compatible, normalize_match_key


BEGIN_RE = re.compile(r"\\begin\{(?P<env>definition|axiom|theorem|lemma|proposition|corollary)\*?\}", re.I)
GENERIC_TITLES = {
    "model",
    "relation",
    "union",
    "intersection",
    "complement",
    "subtraction",
    "interval",
    "supremum",
    "infimum",
    "interior",
    "sequence",
    "ring",
    "polynomial",
    "magma",
    "semigroup",
    "monoid",
    "group",
    "field",
    "theorem",
    "function",
    "operation",
    "inverse",
    "identity",
    "preorder",
    "partial order",
    "total order",
    "left inverse",
    "right inverse",
}
VOLUME_MODULE_PART = {
    "volume-i": "VolumeI",
    "volume-ii": "VolumeII",
    "volume-iii": "VolumeIII",
    "volume-iv": "VolumeIV",
    "volume-v": "VolumeV",
    "volume-vi": "VolumeVI",
    "volume-vii": "VolumeVII",
    "volume-viii": "VolumeVIII",
}


def load_payload(path: Path) -> dict[str, Any]:
    if path.suffix.lower() in {".yaml", ".yml"}:
        return yaml.safe_load(path.read_text(encoding="utf-8"))
    return json.loads(path.read_text(encoding="utf-8"))


def terminal_declaration_name(record: dict[str, Any]) -> str:
    return str(record.get("declaration") or record["name"]).split(".")[-1]


def lean_module_for(record: dict[str, Any]) -> str:
    return str(record.get("module") or "")


def production_lean(record: dict[str, Any]) -> bool:
    return str(record.get("path") or "").startswith("LRA/")


def build_plan(
    payload: dict[str, Any],
    *,
    status: str,
    production_only: bool,
    strict_safe: bool = False,
) -> dict[str, Any]:
    lean_by_key: dict[str, list[dict[str, Any]]] = {}
    for record in payload.get("objects", []):
        if record.get("source_family") != "lean":
            continue
        if production_only and not production_lean(record):
            continue
        key = normalize_match_key(terminal_declaration_name(record))
        lean_by_key.setdefault(key, []).append(record)

    raw_entries = []
    skipped = []
    for tex in payload.get("objects", []):
        if tex.get("source_family") != "tex":
            continue
        if tex.get("metadata", {}).get("starred"):
            skipped.append({"reason": "starred_restatement", "tex_object_id": tex["object_id"]})
            continue
        if "/proofs/" in str(tex.get("path") or ""):
            skipped.append({"reason": "proof_restatement", "tex_object_id": tex["object_id"]})
            continue
        if tex.get("metadata", {}).get("lean_formalizes"):
            skipped.append({"reason": "already_tagged", "tex_object_id": tex["object_id"]})
            continue
        label = tex.get("label")
        if not label:
            skipped.append({"reason": "missing_tex_label", "tex_object_id": tex["object_id"], "path": tex["path"], "line": tex["line"]})
            continue
        key = normalize_match_key(str(tex.get("name") or ""))
        candidates = [
            lean
            for lean in lean_by_key.get(key, [])
            if kind_compatible(str(tex.get("kind")), str(lean.get("kind")))
        ]
        if len(candidates) != 1:
            skipped.append(
                {
                    "reason": "not_unique_exact_match",
                    "tex_object_id": tex["object_id"],
                    "tex_label": label,
                    "tex_name": tex.get("name"),
                    "candidate_count": len(candidates),
                }
            )
            continue
        lean = candidates[0]
        if strict_safe:
            reason = strict_safe_rejection_reason(tex, lean)
            if reason:
                skipped.append(
                    {
                        "reason": reason,
                        "tex_object_id": tex["object_id"],
                        "tex_label": label,
                        "tex_name": tex.get("name"),
                        "lean_object_id": lean["object_id"],
                    }
                )
                continue
        macro = (
            rf"\LeanFormalizes{{{label}}}{{lra-lean}}"
            rf"{{{lean_module_for(lean)}}}{{{terminal_declaration_name(lean)}}}{{{status}}}"
        )
        raw_entries.append(
            {
                "tex_object_id": tex["object_id"],
                "tex_label": label,
                "tex_kind": tex["kind"],
                "tex_name": tex["name"],
                "tex_repo_root": tex["repo_root"],
                "tex_path": tex["path"],
                "tex_line": tex["line"],
                "lean_object_id": lean["object_id"],
                "lean_kind": lean["kind"],
                "lean_module": lean_module_for(lean),
                "lean_declaration": terminal_declaration_name(lean),
                "lean_path": lean["path"],
                "lean_line": lean["line"],
                "status": status,
                "macro": macro,
            }
        )
    entries = choose_one_entry_per_label(raw_entries, skipped)
    return {
        "schema_version": "lra.lean-tex-formalization-plan/1.0",
        "policy": {
            "matching": "exact_normalized_tex_title_to_lean_declaration",
            "production_lean_only": production_only,
            "strict_safe": strict_safe,
            "status": status,
        },
        "counts": {
            "planned": len(entries),
            "skipped": len(skipped),
        },
        "entries": entries,
        "skipped": skipped,
    }


def entry_preference(entry: dict[str, Any]) -> tuple[int, int, str]:
    path = str(entry["tex_path"])
    score = 0
    if "/notes/" in path:
        score += 20
    if path.endswith("/source.tex"):
        score += 15
    if path.endswith("/corrected.tex"):
        score += 5
    if path.endswith("index.tex"):
        score -= 10
    return (-score, len(path), path)


def choose_one_entry_per_label(
    entries: list[dict[str, Any]],
    skipped: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    by_label: dict[str, list[dict[str, Any]]] = {}
    for entry in entries:
        by_label.setdefault(str(entry["tex_label"]), []).append(entry)
    chosen = []
    for label, label_entries in sorted(by_label.items()):
        label_entries.sort(key=entry_preference)
        chosen.append(label_entries[0])
        for duplicate in label_entries[1:]:
            skipped.append(
                {
                    "reason": "duplicate_tex_label_lower_preference",
                    "tex_object_id": duplicate["tex_object_id"],
                    "tex_label": label,
                    "tex_path": duplicate["tex_path"],
                }
            )
    chosen.sort(key=lambda item: (item["tex_path"], item["tex_line"], item["tex_label"]))
    return chosen


def normalized_title(text: str) -> str:
    return normalize_match_key(text)


def strict_safe_rejection_reason(tex: dict[str, Any], lean: dict[str, Any]) -> str | None:
    tex_path = str(tex.get("path") or "")
    tex_volume = tex_path.split("/", 1)[0]
    lean_module = lean_module_for(lean)
    if not tex_path.endswith("/source.tex"):
        return "strict_safe_requires_source_artifact"
    if VOLUME_MODULE_PART.get(tex_volume) not in lean_module:
        return "strict_safe_requires_same_volume"
    title = normalized_title(str(tex.get("name") or ""))
    if title in GENERIC_TITLES:
        return "strict_safe_rejects_generic_title"
    title_tokens = [token for token in title.split() if len(token) > 2]
    if len(title_tokens) <= 1:
        return "strict_safe_rejects_short_title"
    return None


def offset_for_line(text: str, line: int) -> int:
    if line <= 1:
        return 0
    offset = 0
    for _ in range(line - 1):
        found = text.find("\n", offset)
        if found < 0:
            return len(text)
        offset = found + 1
    return offset


def insertion_offset(text: str, entry: dict[str, Any]) -> int:
    start = offset_for_line(text, int(entry["tex_line"]))
    begin = BEGIN_RE.search(text, start)
    if not begin:
        raise ValueError(f"cannot find formal begin for {entry['tex_label']}")
    env = begin.group("env")
    end = re.search(rf"\\end\{{{re.escape(env)}\*?\}}", text[begin.end() :], re.I)
    if not end:
        raise ValueError(f"cannot find formal end for {entry['tex_label']}")
    pos = begin.end() + end.end()
    after = text[pos:]
    box = re.match(r"(?P<ws>\s*)\\end\{(?:definition|axiom|theorem|lemma|proposition|corollary)box\}", after, re.I)
    if box:
        pos += box.end()
    newline = text.find("\n", pos)
    return len(text) if newline < 0 else newline + 1


def apply_plan(plan: dict[str, Any], *, limit: int | None) -> list[dict[str, Any]]:
    applied = []
    for entry in plan.get("entries", [])[:limit]:
        path = Path(entry["tex_repo_root"]) / str(entry["tex_path"])
        text = path.read_text(encoding="utf-8", errors="ignore")
        macro = str(entry["macro"])
        if macro in text:
            applied.append({"path": str(path), "label": entry["tex_label"], "status": "already_present"})
            continue
        pos = insertion_offset(text, entry)
        prefix = "\n" if pos > 0 and text[pos - 1] != "\n" else ""
        updated = text[:pos] + prefix + macro + "\n" + text[pos:]
        path.write_text(updated, encoding="utf-8")
        applied.append({"path": str(path), "label": entry["tex_label"], "status": "inserted"})
    return applied


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--index", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--status", choices=("checked", "statement", "pending", "incomplete"), default="pending")
    parser.add_argument("--include-nonproduction-lean", action="store_true")
    parser.add_argument(
        "--strict-safe",
        action="store_true",
        help="Only plan same-volume, non-generic, source.tex exact matches suitable for first-pass application.",
    )
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--limit", type=int)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = load_payload(args.index)
    plan = build_plan(
        payload,
        status=args.status,
        production_only=not args.include_nonproduction_lean,
        strict_safe=args.strict_safe,
    )
    if args.apply:
        plan["applied"] = apply_plan(plan, limit=args.limit)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(yaml.safe_dump(plan, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"planned {plan['counts']['planned']} tag(s); skipped {plan['counts']['skipped']} object(s)")
    if args.apply:
        print(f"applied {len(plan.get('applied', []))} tag(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
